name: nfvacal

channels:
 - conda-forge
 - bioconda
 - default
dependencies:
 - freebayes=1.3.2
 - samtools=1.12
 - bcftools=1.12
 - vcflib=1.0.2
 - r=4.1
 - r-base=4.1.1
 - r-tidyverse=1.3.1
 - vcftools=0.1.16
